spring:
  profiles:
    active: sample
#  data:
#    mongodb:
#      uri: url
#      database: ${DB_NAME}
#      auto-index-creation: true

  application:
    name: beetexting-task-sample
  datasource:
    url: jdbc:mysql://localhost:3306/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
server:
  port: 8090
  servlet:
    context-path: /beetexting

